"""empty message

Revision ID: 9b57dbe84d37
Revises: a52660341927
Create Date: 2024-02-03 17:52:34.833449

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9b57dbe84d37"
down_revision = "a52660341927"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "rooms", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "rooms", type_="unique")
    # ### end Alembic commands ###
