"""Add Rooms, User, RoomLinkUser Table

Revision ID: 1522526dbc9c
Revises: 668743a5e60c
Create Date: 2024-02-02 07:12:56.460343

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1522526dbc9c"
down_revision = "668743a5e60c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
