"""Add Rooms, User, RoomLinkUser Table

Revision ID: 668743a5e60c
Revises: 25615d348393
Create Date: 2024-02-02 07:05:50.008640

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "668743a5e60c"
down_revision = "25615d348393"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "rooms", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "rooms", type_="unique")
    # ### end Alembic commands ###
