version: 2.1

jobs:
  deploy:
    machine:
      image: buntu-2004:202201-02
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "${KEY_FINGERPRINT}"
      - run:
        name: Add github.com to known hosts
        command: ssh-keyscan -H ${HOST_NAME} >> ./.ssh/known_hosts
      - run:
        name: SSH
        command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${USER_NAME}@${HOST_NAME} 'cd /root/home && touch aaa.txt'

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main