version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "${KEY_FINGERPRINT}"
      - run:
          name: Add github.com to known hosts
          command: ssh-keyscan host ${HOST_NAME} >> $HOME/.ssh/known_hosts
      - run:
          name: SSH
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${USER_NAME}@${HOST_NAME} 'cd /home/iwatagumi/hekuta/MeetUp && git pull origin main && docker compose down -v --rmi all && sudo systemctl restart meetup.service'

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main